version: '3.8'
services:
  postgresdb:
    container_name: postgresInovia
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    ports:
      - '5430:5432'
    volumes:
      - dbpostgres:/var/lib/postgresql/data
    networks:
      - mongo-compose-network

  mongo-express:
    container_name: mongoInovia-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongoInovia
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

  node:
      container_name: nestInovia
      restart: always
      build: ./server
      ports:
        - '3000:3000'
      links:
        - postgresdb
        - mongo
      depends_on:
        - postgresdb
        - mongo
      networks:
        - mongo-compose-network

  web:
      container_name: webInovia
      restart: always
      build: ./web
      ports:
        - '5137:5137'
      links:
        - node
      depends_on:
        - node

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  dbpostgres:
    driver: local
